### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by rikai** [spacechase0/TheftOfTheWinterStar#2]
Hello, not sure what might be causing this, but I am receiving the following error at the start of the first day when this mod is installed and thought it might be worth reporting.

```
This mod failed in the GameLoop.DayEnding event. Technical details:  System.NullReferenceException: Object reference not set to an instance of an object.
    at TheftOfTheWinterStar.Mod.onDayEnding(Object sender, DayEndingEventArgs e) in C:\Programming\StardewValley\ModSource\TheftOfTheWinterStar\Mod.cs:line 295
    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 125
```

**Comment by Neutra1** [comment]
Same error, here is SMAPI log  https://smapi.io/log/cb0cb3d7c0d74235a56d876ef9d04aa5
